runtime: nodejs12
service: backend
env_variables:
  MONGOURI: "mongodb://34.126.175.83:27017/?gssapiServiceName=mongodb"
  PORT: "8000"
  JWT_SECRET: "heybroarihantkjbjkbfjkabfajfbajbadjkfbefjbfjkbfjkbewfeufjkbbuefyeurcbsackjdabvdajkfbejkvdbdbjfbfjefbejkfebf"
  RAZORPAY_SECRET: "12345678"
  ADMINPASSWORD: "admin"
  RAZPORPAY_KEY_ID: "rzp_test_6iKYRtRehIAgwt"
  RAZORPAY_KEY_SECRET: "P0WT57lYBt3MpsyYBPrwrQci"
  PROJECT_ID: "neat-encoder-3"
